### ISSUE TITLE
logo for NotifyAvailability

### ISSUE THREAD

**Issue by hafizahmmed** [xRahul/NotifyAvailability#22]
Hello,
Good Day, i make a logo icon for your project.If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change. which icon you like please tell me.

![notifyavailability-01](https://user-images.githubusercontent.com/38810169/40853035-71493216-65ee-11e8-9e10-ee895bcdf4f1.jpg)

**Comment by xRahul** [comment]
Hey @hafizahmmed 
These look great! I am currently using the default colours in the application and haven't decided on a theme yet.
Have you worked in Android? The last one looks great to me, and according to the android guidelines, this might have to come in multiple sizes. Are you using the [Image Asset Studio](https://developer.android.com/studio/write/image-asset-studio) for this?

**Comment by hafizahmmed** [comment]
![notifyavailability33-01](https://user-images.githubusercontent.com/38810169/40872261-1724bcfe-666d-11e8-9b9f-61a156462485.jpg)


Can i give you Pull request??

**Comment by xRahul** [comment]
sure. This looks great btw! Now I'll set up the theme in these colours too.

**Comment by hafizahmmed** [comment]
sir check here #23

**Comment by hafizahmmed** [comment]
anything problem pull request ???

**Comment by xRahul** [comment]
I have added comments in the PR.

**Comment by hafizahmmed** [comment]
hi sir all file is drive please download this and use this.. https://drive.google.com/open?id=167SF37b6xcjdeceOvGRYTmYWPRcjquWS

i think it's batter for you

**Comment by xRahul** [comment]
okay. Thank you. I'll take the image from there and add it later.
